spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_DEV_URL}
    username: ${DB_DEV_USERNAME}
    password: ${DB_DEV_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 800MB

jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: ${JWT_ACCESS_TOKEN_EXPIRY:3600000}
  refresh-token-expiry: ${JWT_REFRESH_TOKEN_EXPIRY:604800000}

file:
  upload-path: ${FILE_DEV_UPLOAD_PATH}


