spring:
  application:
    name: capstone

  config:
    import: optional:file:.env[.properties]

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight([%-3level]) %cyan(%logger{5}) - %msg%n"